[project]
name = "fundata"
version = "1.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "funshell>=1.0.0",
    "funutil>=1.0.14",
    "tqdm",
]

[dependency-groups]
dev = [
    "pytest>=7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
